/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Abhinav
 */
public class TextSearch extends java.awt.Frame {

    /**
     * Creates new form TextSearch
     */
    public TextSearch() {
        initComponents();
        l1.add("bhopal");
        l1.add("indore");
        l1.add("jabalpur");
        l1.add("bengaluru");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        city = new java.awt.TextField();
        l1 = new java.awt.Choice();

        setMinimumSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setText("Enter city");
        add(label1);
        label1.setBounds(70, 30, 80, 20);

        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        city.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                cityTextValueChanged(evt);
            }
        });
        add(city);
        city.setBounds(300, 30, 170, 20);
        add(l1);
        l1.setBounds(220, 160, 240, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void cityTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_cityTextValueChanged
        String cit=city.getText();
        String arr[]={"bhopal","indore","jabalpur","bengaluru"};
       for(int i=0 ;i<arr.length;i++)
       {
           if(arr[i].startsWith(cit))
           {
               l1.select(i);
           }
       }
        
    }//GEN-LAST:event_cityTextValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextSearch().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField city;
    private java.awt.Choice l1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
