
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Task2 extends java.awt.Frame {

    /**
     * Creates new form Task2
     */
    ResultSet rs;
    public Task2() throws ClassNotFoundException, SQLException {
        initComponents();
        EmployeeDb conn=new EmployeeDb();
       Connection con=conn.getCon();
       PreparedStatement ps=con.prepareStatement("select * from edata",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
       rs=ps.executeQuery();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        eno = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        sal = new javax.swing.JTextField();
        nw = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        jLabel1.setText("Eno");
        add(jLabel1);
        jLabel1.setBounds(20, 110, 60, 14);

        jLabel2.setText("Ename");
        add(jLabel2);
        jLabel2.setBounds(20, 160, 50, 30);

        jLabel3.setText("Salary");
        add(jLabel3);
        jLabel3.setBounds(20, 220, 60, 14);

        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        add(search);
        search.setBounds(10, 300, 100, 23);

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        add(update);
        update.setBounds(130, 300, 100, 23);

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        add(delete);
        delete.setBounds(270, 300, 90, 23);

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        add(save);
        save.setBounds(400, 300, 100, 23);
        add(eno);
        eno.setBounds(120, 100, 280, 30);
        add(ename);
        ename.setBounds(120, 160, 280, 30);
        add(sal);
        sal.setBounds(120, 210, 280, 30);

        nw.setText("NEW");
        nw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nwActionPerformed(evt);
            }
        });
        add(nw);
        nw.setBounds(190, 360, 160, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try {
            // TODO add your handling code here:
            EmployeeDb conn=new EmployeeDb();
            Connection con=conn.getCon();
            int en=Integer.parseInt(eno.getText());
            PreparedStatement ps=con.prepareStatement("select * from edata where eno=?",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ps.setInt(1, en);
             rs=ps.executeQuery();
            if(rs.next()){
                ename.setText(rs.getString(2));
                sal.setText(rs.getString(3));
                
            }
            
               
                    } catch (ClassNotFoundException ex) {
            Logger.getLogger(Task2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Task2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            // TODO add your handling code here:
            rs.updateInt(1,Integer.parseInt(eno.getText()));
            rs.updateString(2,ename.getText());
            rs.updateInt(3,Integer.parseInt(sal.getText()));
            rs.updateRow();
            nw.setEnabled(false);
            search.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(Task2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void nwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nwActionPerformed
        // TODO add your handling code here:
        eno.setText("");
        ename.setText("");
        sal.setText("");
        ename.setEditable(true);
                
        update.setEnabled(false);
        delete.setEnabled(false);
        search.setEnabled(false);
        
    }//GEN-LAST:event_nwActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            // TODO add your
            
            rs.moveToInsertRow();
            rs.updateInt(1,Integer.parseInt(eno.getText()));
            rs.updateString(2,ename.getText());
            rs.updateString(3,sal.getText());
            rs.insertRow();
             update.setEnabled(true);
        delete.setEnabled(true);
        search.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(Task2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            // TODO add your handling code here:
            rs.deleteRow();
        } catch (SQLException ex) {
            Logger.getLogger(Task2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Task2().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Task2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Task2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField eno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton nw;
    private javax.swing.JTextField sal;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
