/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg11.sep.task;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Abhinav
 */
public class Employee extends java.awt.Frame {
ArrayList<Emp> list=new ArrayList<>();


    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        eno = new java.awt.TextField();
        ename = new java.awt.TextField();
        sal = new java.awt.TextField();
        dept = new java.awt.TextField();
        button3 = new java.awt.Button();
        t1 = new java.awt.TextArea();

        setMinimumSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setText("Eno");
        add(label1);
        label1.setBounds(30, 30, 26, 20);

        label2.setText("Ename");
        add(label2);
        label2.setBounds(30, 60, 40, 20);

        label3.setText("Salary");
        add(label3);
        label3.setBounds(30, 90, 38, 20);

        label4.setText("Deptno");
        add(label4);
        label4.setBounds(30, 130, 40, 20);

        button1.setLabel("VIEW");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(70, 170, 45, 24);

        button2.setLabel("ADD");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(170, 170, 41, 24);
        add(eno);
        eno.setBounds(130, 30, 180, 20);

        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });
        add(ename);
        ename.setBounds(130, 60, 180, 20);
        add(sal);
        sal.setBounds(130, 90, 180, 20);
        add(dept);
        dept.setBounds(130, 130, 180, 20);

        button3.setLabel("SAVE");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3);
        button3.setBounds(260, 170, 46, 24);
        add(t1);
        t1.setBounds(60, 220, 280, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameActionPerformed

    public  static void insertEmp(Emp e) throws SQLException, ClassNotFoundException{
        Connection con=OracleDb.getConnnect();
        PreparedStatement ps=con.prepareStatement("insert into empp values(?,?,?,?)");
        ps.setInt(1,e.getEno());
        ps.setInt(2,e.getSal());
        ps.setInt(3,e.getDeptno());
        ps.setString(4,e.getEname());
        ps.executeUpdate();
        
        
    }
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        int en=Integer.parseInt(eno.getText());
        String name=ename.getText();
        int salary=Integer.parseInt(sal.getText());
        int deptno=Integer.parseInt(dept.getText());
        list.add(new Emp(en,name,salary,deptno));
        eno.setText("");
        ename.setText("");
        sal.setText("");
        dept.setText("");
        
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        for(Emp tmp:list){
            t1.append(tmp.getEno()+" "+tmp.getEname()+" "+tmp.getSal()+" "+tmp.getDeptno()+"\n");
            
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        for(Emp e:list){
            try {
                Employee.insertEmp(e);
                eno.setText("");
                ename.setText("");
                sal.setText("");
                dept.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.TextField dept;
    private java.awt.TextField ename;
    private java.awt.TextField eno;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.TextField sal;
    private java.awt.TextArea t1;
    // End of variables declaration//GEN-END:variables
}
